apiVersion: apps/v1
kind: Deployment
metadata:
   name: cwsspot
   annotations:
     # only network load balancer supports static IP
     # service.beta.kubernetes.io/aws-load-balancer-type: nlb
     # comma-separated list of Elastic IP ids
     # the length of the list must be equal to the number of subnets
     service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-00c6829b9415b52ac,eeipalloc-016be9338dd3acb61
   labels:
     app: cwsspot
spec:
   replicas: 1
   selector:
    matchLabels:
      app: cwsspot
   template:
    metadata:
      labels:
        app: cwsspot
    spec:
     containers:
     - name: cwsspot
       image: calixtocws/cwsspot:latest
 #      resources:
       ports:
       - name: hostport
         containerPort: 8883
       - name: clientport
         containerPort: 1883
     nodeSelector:
      alpha.eksctl.io/nodegroup-name: cws-group-public 
