apiVersion: v1
kind: Service
metadata:
  name: my-service-cwsspot
spec:
  selector:
    app: cwsspot
  ports:
  - name: hostport
    port: 8883
    targetPort: 8883
#    nodePort: 30006
  - name: clientport
    port: 1883
    targetPort: 1883
#    nodePort: 30005
  type: LoadBalancer
