apiVersion: v1
kind: Service
metadata:
  name: my-service-cwsspot
  annotations:
    # only network load balancer supports static IP
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # comma-separated list of Elastic IP ids
    # the length of the list must be equal to the number of subnets
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-00c6829b9415b52ac,eipalloc-016be9338dd3acb61,eipalloc-0ce1d9c3386f4fe2c  
spec:
  selector:
    app: cwsspot
  ports:
  - name: hostport
    port: 8883
    targetPort: 8883
#    nodePort: 30006
  - name: clientport
    port: 1883
    targetPort: 1883
#    nodePort: 30005
  type: LoadBalancer
